### ISSUE TITLE
Dateien austauschen

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/webdav#17]
Ich frage mich gerade, ob es über die Webdav-Lösung überhaupt möglich sein wird, Dateien im Medienpool auszutauschen. Wäre ja schon praktisch, gerade bei Bildern und PDFs etc.

Ich denke allerdings, dass eigentlich alle Webdav-Clients daraus ein Löschen und Neuanlegen machen werden.
Das Löschen müsste das webdav-Addon aber ja dann unterbinden, wenn die Datei schon in Verwendung ist, so wie direkt im MP auch.

**Comment by staabm** [comment]
https://github.com/fruux/sabre-dav/issues/948 ;-)

**Comment by staabm** [comment]
habe es implementiert und bin genau auf diese probleme gestoßen.. bin noch unsicher wie man es lösen kann/soll.

**Comment by gharlan** [comment]
Ich fürchte halt, dass die Clients schon selbst erst die Löschoperation ansteuern, und dann anschließend die Erstellung. Daher denke ich, wird da sabre/dav leider auch wenig tun können.

**Comment by staabm** [comment]
vllt kann ich mit einer http-session einen workaround bauen o.ä.

aber ich denke auch dass es irgendwie gehen muss, da ja aktuell jegliche metadaten verloren gehen.

**Comment by gharlan** [comment]
Übrigens nicht nur beim Dateien austauschen, auch beim Dateien bearbeiten machen einige Clients die komischsten Dinge. Eine harmlose Variante ist da noch:
- Neue temporäre Datei
- dann alte löschen
- und dann temporäre umbenennen in richtigen Dateinamen

Andere machen noch viel wildere Dinge.

**Comment by staabm** [comment]
wenn ich den kommentar in `IMoveTarget` richtig lesen wird das vermutlich dann damit gehen oder?
https://github.com/fruux/sabre-dav/blob/4dcc195666e66957350babb19cc728d2d52603c7/lib/DAV/IMoveTarget.php#L25

Du hast das ja auch kürzlich eingebaut im Prozer hab ich gesehen...

**Comment by gharlan** [comment]
`IMoveTarget` greift nur, wenn der Client ein `MOVE ..`-Request absetzt.
Ohne das Interface, macht Sabre/Dav daraus ein copy und delete.
Mit dem Interface kannst du dann direkt verschieben.

Hat aber keine Auswirkung auf die Fälle, wo der Client selbst schon löscht und neu anlegt. Und das machen die Clients halt meist beim direkten Editieren der Dateien.

**Comment by gharlan** [comment]
Also wenn man eine Datei in einen anderen Ordner schiebt, oder einen ganzen Ordner verschiebt, dann machen die Clients eine solche `MOVE ..`-Abfrage.

**Comment by staabm** [comment]
wenn ich nix übersehen habe, sollte dieser punkt der einzige sein den man gelöst bekommen muss vor man eine erste beta rausgeben könnte.

**Comment by staabm** [comment]
weißt du zufällig ob delete+insert in einem php request/response zyklus passiert oder ob es sogar 2 getrennte requests sind?

**Comment by gharlan** [comment]
Du meinst beim direkten Bearbeiten von Dateien?

Transmit.app macht bei Webdav zum Beispiel folgendes, wenn ich eine Datei (`test.txt`) direkt bearbeite:
* Neue Datei `test_safe_save_165805.txt` anlegen mit dem neuen Inhalt
* Alte Datei `test.txt` löschen
* Neue Datei umbenennen in `test.txt`

Es sind in dem Fall also 3 Requests. Sieht im Prozer-Log dann so aus:

<img width="921" alt="screenshot 2017-02-26 17 01 01" src="https://cloud.githubusercontent.com/assets/330436/23341339/c19bc0da-fc45-11e6-8316-483b2f18d76b.png">

Wenn ich mich direkt mit dem Finder über Webdav verbinde (was die meisten Mac-Nutzer wohl tun würden), dann ist es noch viel schlimmer.
Da wird erst ein neuer Ordner erstellt, dann die Originaldatei da rein geschoben, dann noch irgendwie eine andere temporäre Datei erzeugt, die dann wieder umbenannt, und dann dieser temporäre Ordner vom Anfang wieder gelöscht. Irgendwie so, oder so ähnlich war das.

**Comment by gharlan** [comment]
Kennst du eigentlich https://www.charlesproxy.com?
Empfehle ich sehr zum Debugging von WebDav (und auch Caldav/Carddav).
