### ISSUE TITLE
vendor aus Repo raus

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/webdav#7]
Im Core haben wir zwar bisher die vendor-Dirs mit im Repo, ich glaube, ich würde hier aber schonmal dahin übergehen, die nicht mit zu commiten.
Nur in die Releases müssen sie natürlich mit rein (solange wir keine richtige Composer-Integration haben).

**Comment by staabm** [comment]
wurde wieder entfernt.
