### ISSUE TITLE
medien ohne kategorie im root anzeigen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/webdav#8]
alle dateien des medienpool von "keine kategorie" im root...

**Comment by staabm** [comment]
ich habe gar keine rex_media api gefunden um diese auszulesen @gharlan ?

**Comment by gharlan** [comment]
Tatsächlich, da scheint es keine Methode für zu geben. Verrückt.
Sollten wir dann wohl ergänzen. ;)

**Comment by staabm** [comment]
closed by https://github.com/FriendsOfREDAXO/webdav/commit/3885642fd619cdbd5426844f9ff646369de2dec7
