### ISSUE TITLE
Wunsch :: Externes Webdav einbinden (webdav client im redaxo)

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/webdav#9]
Eine Einbindung einer Nextcloudfreigabe wäre genial

**Comment by staabm** [comment]
aktuell ist hier ein caldav server implementiert um die inhalte des medienpool z.b. via netzlaufwerk zu verwenden/anzubieten.

was du willst klingt nach einem caldav client zu einer nextcloud freigabe.. wie genau stellst du dir das vor und was genau erhoffst du dir davon(wie ist der use-case)?

**Comment by gharlan** [comment]
"caldav"? Ich glaube, du meinst jeweils "webdav".. ;)

**Comment by staabm** [comment]
> "caldav"? Ich glaube, du meinst jeweils "webdav".. ;)

stimmt

**Comment by skerbis** [comment]
Eine Webdav-Ressource auch im Medienpool oder in den Artikeln zur Verfügung zu stellen, um z.B. Daten, die in einem Extranet gepflegt werden auch auf der Website nutzen zu können oder zu veröffentlichen. (Scenario: bestimmte Formulare werden im Intranet/Extranet gepflegt und sollen zum aktuellen Stand immer auf der Website zur Verfügung stehen, die Mitarbeiter haben aber keinen Zugriff auf die Webpräsenz)  - Alternativ / Andersrum: Webdav Schreibrechte für Medienpool, was jedoch dazu führen kann, dass Inhalte im Medienpool gelöscht werden könnten.

**Comment by staabm** [comment]
> (Scenario: bestimmte Formulare werden im Intranet/Extranet gepflegt und sollen zum aktuellen Stand immer auf der Website zur Verfügung stehen, die Mitarbeiter haben aber keinen Zugriff auf die Webpräsenz)

in welcher form wird das formular dann zur verfügung gestellt? als html datei die im medienpool liegen soll?

wie würde man metadaten zu den medien pflegen die von einer externen webdav resource zur verfügung stehen?

**Comment by skerbis** [comment]
Formular war wohl eine irreführende Bezeichnung. PDF-Files, Wordfiles... etc. Metas könnten aus dem Dateinamen ermittelt werden (Vorgegebene Schreibweise), oder alternativ aus beiliegender YAML-Datei?  - Oder die Files  und Kategorien werden gesynct und stattdessen müssen die Metas in Redaxo gepflegt werden.

**Comment by staabm** [comment]
würde mit der verwendeten Lib auch funktionieren:
http://sabre.io/dav/davclient/

PR welcome

**Comment by AWqxKAWERbXo** [comment]
Können gute Hoster das nicht ohnehin von Haus aus, ein Verzeichnis als WebDAV einbinden? Wozu der Weg über Redaxo? (Zumindest DF kann es)

Was ist mit Dateinamenskonventionen?

**Comment by staabm** [comment]
> Können gute Hoster das nicht ohnehin von Haus aus, ein Verzeichnis als WebDAV einbinden? Wozu der Weg über Redaxo? (Zumindest DF kann es)

was heißt das ? 

man hat dann einen lokalen filesystem-pfad der auf den webdav server "zeigt"? falls ja wie arbeitet man mit so einem verzeichnis dann mit redaxo?

> Was ist mit Dateinamenskonventionen?

verstehe den zusammenhang nicht. welche konvention und warum?

**Comment by AWqxKAWERbXo** [comment]
**WebDAV bei DF**
Da kann ich einen FTP-Nutzer anlegen, der gleichzeitig auch als WebDAV-Nutzer fungiert. Man kann dann einfach das am FTP-Account hinterlegte Verzeichnis mounten.

**Dateinamen** 
Wenn ich das richtig verstehe, soll der WebDAV-Zugriff später doch nicht nur readonly sein, oder? Ich zieh also eine Datei `mein Beispiel mit schönen umlauten.docx` per webdav in meinem Windows-Explorer auf das WebDAV-Verzeichnis. Wie wird daraus `mein_beispiel_mit_schoenen_umlauten.docx` im Medienpool?

**Comment by staabm** [comment]
> Wenn ich das richtig verstehe, soll der WebDAV-Zugriff später doch nicht nur readonly sein, oder? Ich zieh also eine Datei mein Beispiel mit schönen umlauten.docx per webdav in meinem Windows-Explorer auf das WebDAV-Verzeichnis. Wie wird daraus mein_beispiel_mit_schoenen_umlauten.docx im Medienpool?

aktuell ist es wie im medienpool, d.h. wenn man neue dateien hochlädt und andere mit gleichem namen vorhanden sind wird eine _1 etc. angefügt. sonst bleibts wie es ist.

> Da kann ich einen FTP-Nutzer anlegen, der gleichzeitig auch als WebDAV-Nutzer fungiert. Man kann dann einfach das am FTP-Account hinterlegte Verzeichnis mounten.

und wie nutzt man so ein verzeichnis im redaxo bzw. wie stehen diese inhalte dem redakteur dann zur verfügung?

**Comment by skerbis** [comment]
@alexplusde leider hilft es nichts wenn der Hoster ein Webdav-Ordner mountet. Es geht darum, dass Dateien in einer externen Applikation (z.B. Nextcloud) gepflegt werden, auf die Redakteure im Bedarfsfall über den Medienpool von Redaxo zugreifen können. Entweder um diese direkt zu importieren oder diese direkt zu verwenden. Wenn das OS den Ordner mountet müsste man syncen.

**Comment by AWqxKAWERbXo** [comment]
> und wie nutzt man so ein verzeichnis im redaxo bzw. wie stehen diese inhalte dem redakteur dann zur verfügung?

@staabm man muss dann manuell syncen.

**Comment by AWqxKAWERbXo** [comment]
@skerbis verstehe. geht also darum, dass der Medienpool externe Ressourcen aufnimmt.

**Comment by skerbis** [comment]
Wenn ich aber Teile (bestimmte Kategorien) des Medienpools mounten kann ist es auch ok, dann können die Dateien ja auch aktiv in Nextcloud eingepflegt werden. 
Es müsste aber verhindert werden, dass Dateien gelöscht werden, die aktuell in Redaxo in Verwendung sind. Das Überschreiben von Dateien würde ich aber ggf. (optional) gestattet sehen. Kommt immer auf das Szenario an.

**Comment by AWqxKAWERbXo** [comment]
Sollten solche Rechte evtl. pro Rolle aktiviert / deaktiviert werden können?

**Comment by skerbis** [comment]
Es reicht ausgewählte Kategorien freizugeben, so dass nicht der Komplette MP in z.B. Nextcloud auftaucht.
